# Generated by Django 4.1.7 on 2023-02-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mose_iw28_N1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avis', models.CharField(max_length=200)),
                ('cree_le', models.CharField(max_length=200)),
                ('avis_heure', models.CharField(max_length=200)),
                ('arret', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('equipement', models.CharField(max_length=200)),
                ('machines', models.CharField(max_length=200)),
                ('section', models.CharField(max_length=200)),
                ('ordre', models.CharField(max_length=200)),
                ('grpe_gest_pm', models.CharField(max_length=200)),
                ('centre_de_couts', models.CharField(max_length=200)),
                ('cree_a', models.CharField(max_length=200)),
                ('cree_par', models.CharField(max_length=200)),
            ],
        ),
    ]
