# Generated by Django 4.1.7 on 2023-02-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Correctif', '0002_avis_delete_mose_iw28_n1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probleme', models.CharField(max_length=300)),
                ('action', models.CharField(max_length=300)),
                ('reste_a_faire', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('dht', models.IntegerField()),
            ],
        ),
    ]
