# Generated by Django 4.1.7 on 2023-02-16 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Correctif', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SousEnsemble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='avis',
            name='sous_ensemble_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_ensemble_1', to='Correctif.sousensemble'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='sous_ensemble_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_ensemble_2', to='Correctif.sousensemble'),
        ),
    ]
